# Generated by Django 2.2.3 on 2019-07-25 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20190718_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='empid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='employees',
            name='firstname',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
